[project]
name = "selenium-part4-final"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12.10"
dependencies = [
    "pytest>=8.3.5",
    "selenium>=4.31.0",
]

[tool.pytest.ini_options]
markers = [
    "step_4",
    "step_6",
    "step_8",
]
